version: '3'
services:
  filtable:
    build: .
    container_name: filterable
    ports: 
      - 10000:80
    volumes:
      - .:/var/www/html

networks: 
  default:
    external:
      name: internal